### ISSUE TITLE
Feature Request -- GUI setup for dictionary files

### ISSUE THREAD

**Issue by am2del** [z1dev/zkanji#20]
I'm being a bother again, but this isn't urgent at all - just would be nice if concidered someday later on. Quite easy implementing I think, as it already exist for old user data.

Easing up setup & manual update of dictionary files when flags such as `-i`, `-e` or `-ie` are triggered WITHOUT a specified `PATH`. A simple `GUI_BROWSE` which is triggered upon cases like this, and preferably allow to specify multiple `PATH` - in case user keep files at various locations for some reason.

Why? To simplify the process of adding a starter-option in the `DESKTOP`-file to perform this without needing to open a terminal or use of third-party tools. It will make things more user-friendly for users who aren't used to compiling nor manual install. Though, only *NIX-family systems use DESKTOP-file(s) which support additional `CONTEXT_MENU`-/starter-options. It should be possible to attach similar option to the Windows-version as well - just straight on the `EXEC_CONTEXT_MENU`. _(How to add those is beyond me, but I know it should be possible.)_

When I write the improved `INSTALL`-script, it will include generating a `DESKTOP`-file - it will give more of a professional impression having such ease-of-access options. Getting started with that as soon as the SVG's are finished _(hopefully before February ends)_, unless - of course - you got something you wish for me to prioritize.

In the `DESKTOP`-file it'd be something like:
```
##Define Actions
Actions=Update-Setup-Dictionary-Example;A;

[Desktop Action Update-Setup-Dictionary-Example]
Name=Update or set-up dictionary & example files
Exec=zkanji -ie

[Desktop Action A]
Name=Just because
Exec=zkanji --Flag-for-random-example
##End of actions menu
```

On Linux, in an application menu, instead of regular click - try `MENU_CLICK` on a starter for something like Mozilla Firefox, LibreOffice etc and you'll see a sample of quick-options of this sort.
And yes, I call it `MENU_CLICK` as it's the most accurate - as this world doesn't consist exclusively of right-handed people using traditional PC-style mouse. I wish to cease discrimination of all lefties _(20~25% of the world?)_ as well as all them using stylus, touch-screen, single-button mouse etc.

--

An option, or addition, to above would be to allow zKanji to start without the dictionary files already set up, having an option @ `Dictionary -> Manage dictionaries` where user can select and add/update thus allow on-the-fly adding/updating _while_ using zKanji. On-the-fly would be nice especially for people who got low-spec and don't want to do nothing during the 15~30min it could take them to set up dictionary files. _(When finished, saving to disk as .new, and on next start either rename old to .old - or simply replace the old ones.)_

NOTE:  _This could be a good way to ease up adding support for additional languages later on, as the source used do support more languages in same structure._

**Comment by z1dev** [comment]
(Answering late because I just got through some difficult changes in zkanji.)

> preferably allow to specify multiple PATH - in case user keep files at various locations for some reason.

I'll rather force the users to hold things at a single location if they choose to import stuff without specifying the path on the command line. The reason is simple. Well, laziness mostly. But apart from that, there's already a built in function for browsing for a folder and it doesn't require the program to really be started. Creating a dialog window with selectable options is more work.

I might even change the command line parameters for this. Like -i, -e or -ie will specify what to import and -p or --path would tell the program about the path itself. Someone might write `-i [path] -e` forgetting the path for the examples. Handling cases like that can make the program more complicated.

> And yes, I call it MENU_CLICK as it's the most accurate - as this world doesn't consist exclusively of right-handed people using traditional PC-style mouse. I wish to cease discrimination of all lefties (20~25% of the world?) as well as all them using stylus, touch-screen, single-button mouse etc.

I sometimes use a stylus and it doesn't bother me personally that the secondary click is called right-click. It's just a standardized abstract expression, like so many words used in programs nowadays.

> An option, or addition, to above would be to allow zKanji to start without the dictionary files already set up

I don't understand why this would improve things for users with slow computers. The program can update its main dictionary while running, it just needs a previous dictionary to be around at start up. This will be provided in releases, like it's already done for the Windows version.

If there's a reason it might be worth doing for I can look into it, but zkanji currently needs a complete dictionary to be loaded first for stuff like matching example sentences with words or looking up furigana which is used in some start up stuff. The changes could go too deep and I would rather not do it if possible.

**Comment by z1dev** [comment]
I'll close this as a non-issue. Dictionary import from JMDict sources is present in the main menu. Just use the program with the included dictionary and update it after the program is already running.
